IFNDEF	GAME_SCREENS_INC
GAME_SCREENS_INC		equ<1>

.data
game_level_1_grid			 \
BYTE "------------------------------------------------------------------------------------------------------------------";01
BYTE "|                                                                                                                |";02
BYTE "|                                                                                                                |";03
BYTE "|                                                                                                             X  |";04
BYTE "|                                                                                                                |";05
BYTE "|                                                                                                                |";06
BYTE "|                                                                                                                |";07
BYTE "|                                                                                                                |";08
BYTE "|                                                                                                                |";09
BYTE "|                                                                                                                |";10
BYTE "|                                                                                                                |";11
BYTE "|                                                                                                                |";12
BYTE "|                                                                                                                |";13
BYTE "|                                                                                                                |";14
BYTE "|                                                                                                                |";15
BYTE "|                                                                                                                |";16
BYTE "|                                                                                                                |";17
BYTE "|                                                                                                                |";18
BYTE "|                                                       S                                                        |";19
BYTE "|                                                                                                                |";20
BYTE "|                                                                                                                |";21
BYTE "|                                                                                                                |";22
BYTE "|                                                                                                                |";23
BYTE "|                                                                                                                |";24
BYTE "|                                                                                                                |";25
BYTE "|                                                                                                                |";26
BYTE "|         Z                                                                                                      |";27
BYTE "|                                                                                                                |";28
BYTE "|                                                                                                                |";29
BYTE "|                                                                                                                |";30
BYTE "|                                                                                                                |";31
BYTE "|                                                                                                                |";32
BYTE "|                                                                                                                |";33
BYTE "|                                                                                                                |";34
BYTE "|                                                                                                                |";35
BYTE "|                                                        N                                                       |";36
BYTE "|                                                                                                                |";37
BYTE "---------------------------------------------------------M--------------------------------------------------------";38 
BYTE 00h

game_level_2_grid			 \
BYTE "------------------------------------------------------------------------------------------------------------------";01
BYTE "|                                                                                                                |";02
BYTE "|                                                                                                                |";03
BYTE "|                                                                                                             X  |";04
BYTE "|                                                                                                                |";05
BYTE "|                                                                                                                |";06
BYTE "|                                                                                                                |";07
BYTE "|                                                                                                                |";08
BYTE "|                                                                                                                |";09
BYTE "|                                                                                                             Z  |";10
BYTE "|                                                                                                                |";11
BYTE "|                                                                                                                |";12
BYTE "|                                                                                                                |";13
BYTE "|                                                                                                                |";14
BYTE "|                                                                                                                |";15
BYTE "|                                                                                                                |";16
BYTE "|                                                                                                                |";17
BYTE "|                                                                                                                |";18
BYTE "|                                                       S                                                        |";19
BYTE "|                                                                                                                |";20
BYTE "|                                                                                                                |";21
BYTE "|                                                                                                                |";22
BYTE "|                                                                                                                |";23
BYTE "|                                                                                                                |";24
BYTE "|                                                                                                                |";25
BYTE "|                                                                                                                |";26
BYTE "|                                                                                                                |";27
BYTE "|                                                                                                                |";28
BYTE "|                                                                                                                |";29
BYTE "|                                                                                                                |";30
BYTE "|                                                                                                                |";31
BYTE "|                                                                                                                |";32
BYTE "|                                                                                                                |";33
BYTE "|                                                                                                                |";34
BYTE "|                                                                                                                |";35
BYTE "|                                                       N                                                        |";36
BYTE "|                                                                                                                |";37
BYTE "--------------------------------------------------------M---------------------------------------------------------";38 
BYTE 00h

game_level_3_grid			 \
BYTE "------------------------------------------------------------------------------------------------------------------";01
BYTE "|                                                                                                                |";02
BYTE "|                                                                                                                |";03
BYTE "|                                                                                                                |";04
BYTE "|                                                                                                                |";05
BYTE "|                                                                                                                |";06
BYTE "|                                                                                                                |";07
BYTE "|                                                                                                                |";08
BYTE "|                                                                                                                |";09
BYTE "|                                                                                                                |";10
BYTE "|                                                                                                                |";11
BYTE "|                                                                                                                |";12
BYTE "|                                                                                                                |";13
BYTE "|                                                                                                                |";14
BYTE "|                                                                                                                |";15
BYTE "|                                                                                                                |";16
BYTE "|                                                                                                                |";17
BYTE "|                                                                                                                |";18
BYTE "|                                                       S                                                        |";19
BYTE "|                                                                                                                |";20
BYTE "|                                                                                                                |";21
BYTE "|                                                                                                                |";22
BYTE "|                                                                                                                |";23
BYTE "|                                                                                                                |";24
BYTE "|                                                                                 Z                              |";25
BYTE "|                                                                                                                |";26
BYTE "|                                                                                                                |";27
BYTE "|                                                                                                                |";28
BYTE "|                                                                                                                |";29
BYTE "|                                                                                                                |";30
BYTE "|                                                                                                                |";31
BYTE "|                                                                                                                |";32
BYTE "|                                                                                                                |";33
BYTE "|                                                                                                            X   |";34
BYTE "|                                                                                                                |";35
BYTE "|                                                       N                                                        |";36
BYTE "|                                                                                                                |";37
BYTE "--------------------------------------------------------M---------------------------------------------------------";38 
BYTE 00h

ELSE 
echo error warning game_screens.inc redeclared
echo error warning game_screens.inc redeclared
echo error warning game_screens.inc redeclared
ENDIF